# Generated by Django 5.0.3 on 2024-03-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
