services:

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_DATABASE=storefront
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p12345"]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DB=storefront
    ports:
      - "8000:8000"
    command: sh -c "python3 manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
